routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Slide;

Route::group(
[
	'prefix' => LaravelLocalization::setLocale(),
	'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
],
function()
{

/* Front end */
Route::get('/', 'MainController@index');
Route::get(LaravelLocalization::transRoute('routes.blog'), ['as' => 'blog', 'uses' => 'MainController@blogs']);
Route::get(LaravelLocalization::transRoute('routes.career'), ['as' => 'career', 'uses' => 'MainController@career_page']);
Route::get(LaravelLocalization::transRoute('routes.portfolio'), ['as' => 'portfolio', 'uses' => 'MainController@portfolio']);
Route::get(LaravelLocalization::transRoute('routes.about'), ['as' => 'about', 'uses' => 'MainController@about']);
Route::get(LaravelLocalization::transRoute('routes.contact'), ['as' => 'contact', 'uses' => 'MainController@contact']);
Route::get(LaravelLocalization::transRoute('routes.post'), ['as' => 'post', 'uses' => 'MainController@post']);
Route::get(LaravelLocalization::transRoute('routes.notFound'), ['as' => 'notFound', 'uses' => 'MainController@error']);
//Route::get('/blogpost/{slug}', 'MainController@post');
Route::get('/client/{slug}', 'MainController@client');
Route::post('/contact', 'MainController@postcontact');
Route::post('/career', 'MainController@career');
Route::post('/homecontact', 'MainController@homecontact');

// clients
Route::get(LaravelLocalization::transRoute('routes.bimilk'), ['as' => 'bimilk', 'uses' => 'AllClientsController@bimilk']);
Route::get(LaravelLocalization::transRoute('routes.linea'), ['as' => 'linea', 'uses' => 'AllClientsController@linea']);
Route::get(LaravelLocalization::transRoute('routes.balans'), ['as' => 'balans', 'uses' => 'AllClientsController@balans']);
Route::get(LaravelLocalization::transRoute('routes.zito'), ['as' => 'zito', 'uses' => 'AllClientsController@zito']);
Route::get(LaravelLocalization::transRoute('routes.cineplexx'), ['as' => 'cineplexx', 'uses' => 'AllClientsController@cineplexx']);
Route::get(LaravelLocalization::transRoute('routes.forza'), ['as' => 'forza', 'uses' => 'AllClientsController@forza']);
});
//LANGUAGE SWITCHER
// Route::get('lang/{language}', ['as' => 'lang.switch', 'uses' => 'LanguageController@switchLang']);


Route::group(['middleware' => ['web'], 'prefix' => LaravelLocalization::setLocale().'/admin'], function () {
    Auth::routes();
    Route::get('logout', 'Auth\LoginController@logout');
});

/* Back end */
Route::group(['middleware' => ['web'], 'prefix' => LaravelLocalization::setLocale().'/admin'], function () {


    Route::get('/', 'SettingsController@index');
    Route::get('/settings', 'SettingsController@index')->name('admin.settings.index');
    Route::post('/settings/store', 'SettingsController@store')->name('admin.settings.store');
    Route::get('/settings/{id}/edit', 'SettingsController@edit')->name('admin.settings.edit');
    Route::post('/settings/update', 'SettingsController@update')->name('admin.settings.update');
    Route::resource('/scripts', 'ScriptsController');
    Route::resource('/categories', 'CategoriesController');
    Route::resource('/users', 'UserController');
    Route::get('/oauth', function () {
        return view('admin.oauth.index');
    });
    Route::get('/slider', 'SliderController@index')->name('admin.slider');
    //POST METHOD FOR SLIDER
    Route::post('slider/create','SliderController@create')->name('admin.slider.create');
    Route::get('slider/{id}/edit', 'SliderController@edit')->name('admin.slider.edit');
    Route::put('slider/update/{id}','SliderController@update')->name('admin.slider.update');
    Route::post('slider/delete/{id}','SliderController@delete')->name('admin.slider.delete');

    //Blog

//    Route::resource('/blog', 'BlogController');
    Route::resource('/blog', 'NewBlogController');
    Route::get('/blog/{id}/posts', 'NewBlogController@postsindex')->name('list.blog.posts');
    Route::get('/blog/{id}/create/post', 'NewBlogController@createpost')->name('create.blog.post');
    Route::get('/blog/{id}/edit/post/{post_id}', 'NewBlogController@editpost')->name('edit.blog.post');
    Route::post('/blog/store/post','NewBlogController@storepost')->name('admin.blogpost.create');
    Route::patch('blog/update/post/{post_id}','NewBlogController@updatepost')->name('admin.blogpost.update');

    Route::get('/blog/{id}/trash', 'NewBlogController@trash');
    Route::post('/blog/delete/post/{id}','NewBlogController@destroypost')->name('admin.blogpost.softdelete');
    Route::post('/blog/empty/trash','NewBlogController@emptytrash')->name('empty.trash');
    Route::post('/blog/permanent/post/{id}','NewBlogController@permanentdeleteitem')->name('admin.blogpost.harddelete');
    Route::post('/blog/restore/post/{id}','NewBlogController@restoreitem')->name('admin.blogpost.restore');

    //Clients
    Route::resource('/clients', 'ClientController');

    //About us
    Route::get('/about', 'AboutUsController@index')->name('admin.about.index');
    Route::get('/about/create', 'AboutUsController@create')->name('admin.about.create');
    Route::post('/about/create', 'AboutUsController@store')->name('admin.about.store');
    Route::patch('/about/update', 'AboutUsController@update')->name('admin.about.update');

    //Team
    Route::resource('/team', 'TeamController');



});

app/NewBlog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Dimsav\Translatable\Translatable;

class NewBlog extends Model
{
    use Translatable;

    public $translatedAttributes = ['name', 'slug', 'description'];
    protected $table = 'new_blogs';
    protected $fillable = [
        'id',
        'name',
        'description',
        'user_id',
        'created_at',
        'updated_at'
    ];

}

app/Http/Controllers/NewBlogController.php
<?php

namespace App\Http\Controllers;

use App\NewBlog;
use App\Category;
use App\NewBlogTranslation;
use App\NewPost;
use App\NewPostTranslation;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Validator;
use Input;
use Session;
use Intervention\Image\ImageManagerStatic as Image;
use App\Client;

class NewBlogController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    //INDEX METHOD:GET
    public function index()
    {
        $blogs = NewBlog::all()->sortBy('created_at');
        $posts = NewPost::all();
        $blogCategories = Category::all();
        $trashed = NewPost::onlyTrashed()->get();
        $data = ['blogs' => $blogs, 'blogCategories' => $blogCategories, 'posts'=>$posts, 'trashed'=>$trashed];
        return view('admin.newblog.index')->with($data);

    }

    //CREATE METHOD:GET

    public function create()
    {
        return view('admin.newblog.create');
    }


    //SAVE METHOD:POST

    public function store(Request $request)
    {
        $errors = Validator::make($request->all(), [
            'name' => 'required|max:255',
        ]);

        if ($errors->fails()) {
            return redirect()->back()
                ->withErrors($errors)
                ->withInput();
        }

//        $request['slug'] = str_slug($request['name']);
//        $slug = NewBlog::where('name', $request['name'])->get();
//        if (count($slug) > 0) {
//            $request['slug'] = $request['slug'] . '-' . count($slug);
//        } else {
//            $request['slug'] = $request['slug'];
//        }
//
//        $input = $request->all();
//
//        NewBlog::create($input);

            $blog = new NewBlog;
            $blog->name = $request['name'];
            $blog->description = $request['description'];
            $blog->save();

        Session::flash('flash_message', 'Blog successfully created!');

        return redirect()->route('blog.index');
    }



    // EDIT VIEW METHOD:GET

    public function edit($id)
    {
        $blogDetails = NewBlog::FindOrFail($id);
        $data = ['blog' => $blogDetails];

        return view('admin.newblog.edit')->with($data);
    }

    // UPDATE BLOG METHOD:PUT

    public function update(Request $request, $id)
    {
        $errors = Validator::make($request->all(), [
            'name' => 'required|max:255',
        ]);

        if ($errors->fails()) {
            return redirect()->back()
                ->withErrors($errors)
                ->withInput();
        }

        $blog = NewBlog::FindOrFail($id);
        $input = $request->all();

        $blog->fill($input)->save();

        Session::flash('flash_message', 'Blog successfully edited!');

        return redirect('/admin/blog');


    }

    //DELETE BLOG METHOD:DELETE

    public function destroy($id)
    {
        $blog = NewBlog::FindOrFail($id);
        $translations = NewBlogTranslation::where('new_blog_id', '=', $id);

        $translations->delete();
        $blog->delete();

        Session::flash('flash_message', 'Blog successfully deleted!');
        return redirect('/admin/newblog');
    }


    /*
   *************************************************************
   *************************************************************
   **************    BLOG POSTS CONTROLLERS       **************
   *************************************************************
   *************************************************************

   */

    public function postsindex($id)
    {
        $blog = NewBlog::FindOrFail($id);
        $posts = NewPost::all()->sortBy('created_at')->where('blog_id', $id);
        $trashed = NewPost::onlyTrashed()->get();
        $blogCategory = Category::Find($id);
        $data = ['posts' => $posts, 'blog' => $blog , 'trashed' => $trashed, 'blogCategory' => $blogCategory];

        return view('admin.newblog.posts')->with($data);


    }

    public function trash($id)
    {
        $blog = NewBlog::FindOrFail($id);
        $trashed = NewPost::onlyTrashed()->get();
        $posts = NewPost::all()->sortBy('created_at')->where('blog_id', $id);

        $data = ['posts' => $posts, 'blog' => $blog , 'trashed' => $trashed];

        return view('admin.newblog.posts.trashed')->with($data);


    }

    //Create post

    public function createpost($id)
    {
        $blog = NewBlog::FindOrFail($id);
        $categories = Category::all();
        $data = ['blog' => $blog, 'categories' => $categories];

        return view('admin.newblog.posts.create')->with($data);
    }

    //Store post

    public function storepost(Request $request)
    {
        $errors = Validator::make($request->all(), [
            'title' => 'required|max:255',
            'content' => 'required',
            'category' => 'required',
            'image' => 'required',
            'excerpt' => 'required',
        ]);

        if ($errors->fails()) {
            return redirect()->back()
                ->withErrors($errors)
                ->withInput();
        }


//        $input = $request->all();


        if ($request->hasFile('image')) {

            $image = $request->file('image');
            $path = public_path() . '/assets/img/posts-images/';
            $pathThumb = public_path() . '/assets/img/posts-images/thumbnails/';
            $pathMedium = public_path() . '/assets/img/posts-images/medium/';
            $title = $request->input('title');
            $name = str_slug($title, '-');
            $ext = '.'.$image->getClientOriginalExtension();

            $checkimage = NewPostTranslation::where('image','LIKE', '%'.$name.'%')->get();

            if(count($checkimage)> 0 ){
                $imageName = $name. '-' . count($checkimage) . $ext;
            } else{
                $imageName = $name . $ext;
            }

            $image->move($path, $imageName);

            $findimage = public_path() . '/assets/img/posts-images/' . $imageName;
            $imagethumb = Image::make($findimage)->resize(200, null, function ($constraint) {
                $constraint->aspectRatio();
            });

            $imagemedium = Image::make($findimage)->resize(600, null, function ($constraint) {
                $constraint->aspectRatio();
            });

            $imagethumb->save($pathThumb . $imageName);
            $imagemedium->save($pathMedium . $imageName);

            $image = $request->imagethumb = $imageName;
            $imagethumb = $request->image = $imageName;
            $imagemedium = $request->image = $imageName;

//            $input['image'] = $image;
//            $input['imageomedium'] = $imagemedium;
//            $input['imagethumb'] = $imagethumb;

        }

//        $checkSlug = BlogPost::where('slug','LIKE', '%'.$name.'%')->get();
//        $slug = str_slug($title, '-');
//
//        if(count($checkSlug)> 0 ){
//            $input['slug'] = $slug. '-' . count($checkSlug);
//        } else{
//            $input['slug'] = $slug;
//        }

        $post = new NewPost;

        $post->title = $request->title;
        $post->content = $request->content;
        $post->excerpt = $request->excerpt;
        $post->image = $image;
        $post->imageomedium = $imagethumb;
        $post->imagethumb = $imagemedium;
        $post->blog_id = $request->blog_id;
        $post->user_id = $request->user_id;
        $post->category = $request->category;

        $post->save();



//        BlogPost::create($input);

        Session::flash('flash_message', 'Post successfully created!');

        return redirect()->action('NewBlogController@index');
    }

    //Edit Post View

    public function editpost($id, $post_id)
    {
        $blog = NewBlog::FindOrFail($id);
        $categories = Category::all();
        $post = NewPost::FindOrFail($post_id);

        $data = ['blog' => $blog, 'categories' => $categories, 'post' => $post];

        return view('admin.newblog.posts.edit')->with($data);

    }


    //UPDATING POST

    public function updatepost(Request $request, $post_id)
    {
        $errors = Validator::make($request->all(), [
            'title' => 'required|max:255',
            'content' => 'required',
            'category' => 'required',
            'excerpt' => 'required'
        ]);

        if ($errors->fails()) {
            return redirect()->back()
                ->withErrors($errors)
                ->withInput();
        }

        $post = NewPost::FindOrFail($post_id);
        $input = $request->all();

        if ($request->hasFile('image')) {

            $image = $request->file('image');
            $path = public_path() . '/assets/img/posts-images/';
            $pathThumb = public_path() . '/assets/img/posts-images/thumbnails/';
            $pathMedium = public_path() . '/assets/img/posts-images/medium/';
            $title = $request->input('title');
            $name = str_slug($title, '-');
            $ext = '.'.$image->getClientOriginalExtension();

            $checkimage = NewPostTranslation::where('image','LIKE', '%'.$name.'%')->get();

            if(count($checkimage)> 0 ){
                $imageName = $name. '-' . count($checkimage) . $ext;
            } else{
                $imageName = $name . $ext;
            }

            $image->move($path, $imageName);

            $findimage = public_path() . '/assets/img/posts-images/' . $imageName;
            $imagethumb = Image::make($findimage)->resize(200, null, function ($constraint) {
                $constraint->aspectRatio();
            });

            $imagemedium = Image::make($findimage)->resize(600, null, function ($constraint) {
                $constraint->aspectRatio();
            });

            $imagethumb->save($pathThumb . $imageName);
            $imagemedium->save($pathMedium . $imageName);

            $image = $request->imagethumb = $imageName;
            $imagethumb = $request->image = $imageName;
            $imagemedium = $request->image = $imageName;

resources/views/admin/newblog/create.blade.php
@extends('layouts.app')


@section('content')
    <div class="page-body">
        <div class="row">
            <div class="col-lg-offset-1 col-sm-offset-1 col-lg-10 col-sm-12 col-xs-12">

                @if(Session::has('flash_message'))
                    <div class="alert alert-success">
                        {{ Session::get('flash_message') }}
                    </div>
                @endif

                <div class="widget">
                    <div class="widget-header bordered-bottom bordered-warning">
                        <span class="widget-caption">Add Blog</span>
                    </div>

                    <div class="widget-body">
                        <div id="horizontal-form">

                            {{ Form::model('newblog', array('route' => array('blog.store'), 'method' => 'POST', 'files'=>true)) }}

                            <div class="form-group">
                                <label for="title">Blog name</label>
                                <input type="text" name="name" class="form-control" value="{{old('title')}}">
                            </div>
                            @if ($errors->has('name')) <p
                                    class="alert alert-danger">{{ $errors->first('name') }}</p> @endif

                            <div class="form-group">
                                <label for="description">Description</label>
                                <textarea class="ckeditor" id="elm3" name="description"></textarea>
                            </div>
                            @if ($errors->has('description')) <p
                                    class="alert alert-danger">{{ $errors->first('description') }}</p> @endif

                        <!-- Hidden inputs -->

                            <input type="hidden" name="user_id" value="{{ Auth::user()->id  }}">

                            <button type="submit" class="btn btn-labeled shiny btn-warning btn-large"><i
                                        class="btn-label fa fa-plus"></i> Save
                            </button>


                            {!! Form::close() !!}


                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>



@endsection

resources/views/admin/newblog/edit.blade.php
@extends('layouts.app')


@section('content')
    <div class="page-body">
        <div class="row">
            <div class="col-lg-offset-1 col-sm-offset-1 col-lg-10 col-sm-12 col-xs-12">

                @if(Session::has('flash_message'))
                    <div class="alert alert-success">
                        {{ Session::get('flash_message') }}
                    </div>
                @endif

                <div class="widget">
                    <div class="widget-header bordered-bottom bordered-warning">
                        <span class="widget-caption">Edit Blog</span>
                    </div>

                    <div class="widget-body">
                        <div id="horizontal-form">

                            {{ Form::model('newblog', array('route' => array('blog.update', $blog->id), 'method' => 'PUT', 'files'=>true)) }}

                            <div class="form-group">
                                <label for="title">Blog name</label>
                                <input type="text" name="name" class="form-control" value="{{$blog->name}}">
                            </div>
                            @if ($errors->has('name')) <p
                                    class="alert alert-danger">{{ $errors->first('name') }}</p> @endif

                            <div class="form-group">
                                <label for="description">Description</label>
                                <textarea class="ckeditor" id="elm3" name="description">{!! $blog->description !!}</textarea>
                            </div>
                            @if ($errors->has('description')) <p
                                    class="alert alert-danger">{{ $errors->first('description') }}</p> @endif

                        <!-- Hidden inputs -->

                            {{--<input type="hidden" name="user_id" value="{{ Auth::user()->id  }}">--}}

                            <button type="submit" class="btn btn-labeled shiny btn-warning btn-large"><i
                                        class="btn-label fa fa-plus"></i> Save
                            </button>

                            <!-- Button trigger modal -->
                            <button data-link="{{url('/')}}/admin/blog/{{$blog->id}}" type="button" class="btn btn-labeled shiny btn-warning btn-large deleteSlideModal" data-toggle="modal" data-target="#deleteSlide">
                                <span class="btn-label g glyphicon glyphicon-trash" aria-hidden="true"></span> Delete
                            </button>

                            <a href="/admin/blog" class="btn btn-labeled shiny btn-warning btn-large">
                                <i class="btn-label fa fa-chevron-left" aria-hidden="true"></i> Back
                            </a>


                            {!! Form::close() !!}


                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>


    <!-- Modal -->
    <div class="modal fade" id="deleteSlide" tabindex="-1" role="dialog" aria-labelledby="deleteSlide">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="deleteSlideLabel">Are you sure you want to delete this blog?</h4>
                </div>
                <div class="modal-body">
                    {{ Form::model('newblog', array('route' => array('blog.destroy', $blog->id), 'method' => 'DELETE', 'id' => 'blog'))}}
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">



                        <button  type="submit" class="btn btn-labeled shiny btn-warning btn-large">
                            <span class="btn-label g glyphicon glyphicon-trash" aria-hidden="true"></span> Delete
                        </button>

                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/admin/newblog/index.blade.php
@extends('layouts.app')


@section('content')

    <div class="page-body">
        <div class="row">
            <div class="col-lg-12">

                @if(Session::has('flash_message'))
                    <div class="alert alert-success">
                        {{ Session::get('flash_message') }}
                    </div>
                @endif


                <p><a class="btn btn-labeled shiny btn-warning btn-large" href="/admin/blog/create"> <i
                                class="btn-label fa fa-plus"></i>Add Blog </a></p>
            </div>


            <div class="col-lg-12">
                <div class="widget">
                    <div class="widget-header bordered-bottom bordered-themesecondary">
                        <i class="widget-icon fa fa-tags themesecondary"></i>
                        <span class="widget-caption themesecondary">Blogs</span>
                    </div><!--Widget Header-->
                    <div class="widget-body  no-padding">
                        <div class="tickets-container">

                            @if($blogs->isEmpty())
                                <p>There aren't any blogs yet please add <a href="/admin/blog/create"> new</a>.</p>
                            @else

                                <table class="table table-hover table-striped table-bordered" width="100%" border="0" cellspacing="0" cellpadding="20">
                                    <thead class="bordered-blueberry">
                                    <tr>
                                        <th>Name</th>
                                        <th>Slug</th>
                                        <th>Number of posts</th>
                                        <th>Manage</th>
                                    </tr>
                                    </thead>

                                    <tbody>

                                    @foreach($blogs as $blog)
                                        <tr  valign="middle">
                                            <td>{{$blog->name}}</td>
                                            <td>{{$blog->slug}}</td>
                                            <td>{{count($posts->where('blog_id', $blog->id))}}</td>
                                            <td>
                                                    <span style="float: right;">

                                                        <a class="manageSlideBtn" href="{{route('create.blog.post', $blog->id)}}"> Add Post</a>

                                                         <a type="button" class="manageSlideBtn" id="{{$blog->id}}" href="{{route('list.blog.posts', $blog->id)}}">
                                                            See posts
                                                        </a>

                                                         <a type="button" class="manageSlideBtn" id="{{$blog->id}}" href="{{route('blog.edit', $blog->id)}}">
                                                            Edit
                                                        </a>

                                                        @if (count($trashed)> 0)

                                                            <a type="button" class="manageSlideBtn" id="{{$blog->id}}" href="/admin/blog/{{$blog->id}}/trash">
                                                            Trashed ({{count($trashed)}})
                                                             </a>

                                                        @endif

                                                        </span>

                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            @endif

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

@endsection

resources/views/admin/newblog/posts.blade.php
@extends('layouts.app')


@section('content')

    <div class="page-body">
        <div class="row">
            <div class="col-lg-12">

                @if(Session::has('flash_message'))
                    <div class="alert alert-success">
                        {{ Session::get('flash_message') }}
                    </div>
                @endif


                <p><a class="btn btn-labeled shiny btn-warning btn-large" href="{{route('create.blog.post', $blog->id)}}"> <i
                                class="btn-label fa fa-plus"></i>Add Post </a></p>
            </div>

            <div class="col-lg-12">
                Published posts ({{count($posts)}}) |   <a href="/admin/blog/{{$blog->id}}/trash" > Trash ({{count($trashed)}}) </a>
            </div>


            <div class="col-lg-12">
                <div class="widget">
                    <div class="widget-header bordered-bottom bordered-themesecondary">
                        <i class="widget-icon fa fa-tags themesecondary"></i>
                        <span class="widget-caption themesecondary">Posts from {{$blog->name}}</span>
                    </div><!--Widget Header-->
                    <div class="widget-body  no-padding">
                        <div class="tickets-container">

                            @if($posts->isEmpty())
                                <p>There aren't any posts yet please add <a href="{{route('create.blog.post', $blog->id)}}"> new</a>.</p>
                            @else

                                <table class="table table-hover table-striped table-bordered" width="100%" border="0" cellspacing="0" cellpadding="20">
                                    <thead class="bordered-blueberry">
                                    <tr>
                                        <th>Name</th>
                                        <th>Slug</th>
                                        <th>Manage</th>
                                    </tr>
                                    </thead>

                                    <tbody>

                                    @foreach($posts as $post)
                                        <tr  valign="middle">
                                            <td>{{$post->title}}</td>
                                            <td>{{$post->slug}}</td>
                                            <td>
                                                    <span style="float: right;">
                                                    <a type="button" class="manageSlideBtn" id="{{$post->id}}" href="{{route('edit.blog.post', array('id' =>  $blog->id, 'post_id' => $post->id))}}">
                                                        Edit
                                                    </a>

                                                        <form class="inlineForm" action="{{route('admin.blogpost.softdelete', $post->id)}}"  method="POST" accept-charset="UTF-8" enctype="multipart/form-data">
                                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                            <button  type="submit" class="manageSlideBtn">
                                                                Delete
                                                            </button>
                                                        </form>

                                                        </span>

                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            @endif

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>



@endsection